//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Envio
    {
        public long ID { get; set; }
        public long NroTracking { get; set; }
        public double PrecioTotal { get; set; }
        public string Estado { get; set; }
        public string IDFuncionario { get; set; }
        public long IDRemitente { get; set; }
        public long IDDestinatario { get; set; }
        public string IDTipoPago { get; set; }
        public string IDCamion { get; set; }
        public long IDZona { get; set; }
        public long IDDireccion { get; set; }
    }
}
